# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 18:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0005_auto_20171113_1817'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
    ]
