# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0007_auto_20171113_1917'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
