# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0015_auto_20171117_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
                ('post', models.ManyToManyField(to='simpleblog.Post')),
            ],
        ),
    ]
